server:
  port: 8080
  data-path: ${user.dir}
  servlet.session.timeout: 60m
  # TOMCAT
  tomcat:
    max-http-form-post-size: 20MB
    accept-count: 100
    max-connections: 200
    connection-timeout: 30000
    threads:
      max: 50
      min-spare: 10

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %5p %X{PID} --- [%thread] %logger{36}:%L - %msg%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} %5p %X{PID} --- [%thread] %logger{36}:%L - %msg%n"
  file.name: ${server.data-path}/logs/frontend/frontend.log
  logback.rollingpolicy:
    file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
    max-file-size: 1GB
    max-history: 7

spring:
  # thymeleaf
  thymeleaf.mode: HTML
